services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  search:
    build:
      context: services
      dockerfile: search/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - search_data:/app/badger

  query-api:
    build:
      context: services/query-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - search
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SEARCH_HOST=search
      - SEARCH_PORT=50051
    volumes:
      - ./services/query-api:/app

  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - query-api
    environment:
      - VITE_QUERY_API_URL=http://localhost:8000
    volumes:
      - ./webapp:/app
      - /app/node_modules

volumes:
  redis_data:
  search_data:
